### ISSUE TITLE
Cleanup script - missing dependencies

### ISSUE THREAD

**Issue by dazdaz** [GoogleCloudPlatform/bank-of-anthos-scripts#1]
When I run the cleanup script, some scripts appear to be missing :

./env: line 10: /home/user/bank_of_anthos/bank-of-anthos-scripts/install/common/manage-state.sh: No such file or directory
./env: line 11: load_state: command not found
WORK_DIR set to /home/user/bank_of_anthos/bank-of-anthos-scripts/install/workdir
Updated property [core/project].
./cleanup.sh: line 32: ./connect-hub/cleanup-hub.sh: No such file or directory

**Comment by meganokeefe** [comment]
Thanks for this! Cleanup script updated. 
https://github.com/GoogleCloudPlatform/bank-of-anthos-scripts/blob/master/install/cleanup.sh
