### ISSUE TITLE
Support for running bootstrap.sh from GCP GCE (Ubuntu VM)

### ISSUE THREAD

**Issue by dazdaz** [GoogleCloudPlatform/bank-of-anthos-scripts#2]
Support for running the bootstrap.sh script from GCP GCE (Ubuntu VM).

Right now, the script is doing this check :
if [[ $OSTYPE == "linux-gnu" && $CLOUD_SHELL == true ]]; then

I'm not sure what pre-requisites need to be in place, but will certainly require :

kubectl
helm
kops
gcloud
kubectx
nomos
git

**Comment by meganokeefe** [comment]
Hello, currently these scripts only work on Cloud Shell (Debian) but I'll leave this issue open if we get a chance to support Ubuntu as well.
